# Version: 0.0.1
FROM ubuntu:18.04
MAINTAINER Seung-hwan Linus Lee "yish8213@gmail.com"
ENV REFRESHED_AT 2018-03-04
RUN apt-get -q update
RUN apt-get -y upgrade
RUN apt-get install -y openjdk-9-jre-headless
EXPOSE 8080
