# Version: 0.0.1
FROM ubuntu:17.04
MAINTAINER Seung-hwan Linus Lee "yish8213@gmail.com"
ENV REFRESHED_AT 2017-03-30
RUN apt-get -q update
RUN apt-get -y upgrade
RUN apt-get install -y openjdk-8-jre-headless
EXPOSE 8080
