version: '3.1'
services:
   mysql:
     image: mariadb:11.4.5
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: r00t!
       MYSQL_DATABASE: ROPPA
       MYSQL_USER: roppa
       MYSQL_PASSWORD: r0ppa!
       MYSQL_CHARSET: utf8
       MYSQL_DATABASE_CHARSET: utf8
     ports:
       - "3306:3306"
   redis:
     image: redis:7.4.2-alpine
     restart: always
     ports:
       - "6379:6379"
volumes:
    db_data:
